<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>.\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Toolbox\bin\Release\Lib\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BrawlLib">
      <HintPath>..\Toolbox\Lib\BrawlLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Gl_EditorFramework">
      <HintPath>..\Toolbox\Gl_EditorFramework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Syroot.BinaryData">
      <HintPath>..\Toolbox\Lib\Syroot.BinaryData.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Syroot.Maths">
      <HintPath>..\Toolbox\Lib\Syroot.Maths.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Syroot.NintenTools.Bfres, Version=1.2.3.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Toolbox\Lib\Syroot.NintenTools.Bfres.dll</HintPath>
    </Reference>
    <Reference Include="Syroot.NintenTools.NSW.Bfres, Version=1.2.3.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Toolbox\Lib\Syroot.NintenTools.NSW.Bfres.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Switch_Toolbox_Library\Toolbox_Library.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>