<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>FirstPlugin</RootNamespace>
    <AssemblyName>FirstPlugin.Plg</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Toolbox\bin\Debug\Lib\Plugins\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Toolbox\bin\Release\Lib\Plugins\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AampLibraryCSharp">
      <HintPath>..\Toolbox\Lib\AampLibraryCSharp.dll</HintPath>
    </Reference>
    <Reference Include="BarsLibrary">
      <HintPath>..\Toolbox\Lib\BarsLibrary.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BcresLibrary, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Toolbox\Lib\BcresLibrary.dll</HintPath>
    </Reference>
    <Reference Include="BfshaLibrary, Version=1.2.3.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Toolbox\Lib\BfshaLibrary.dll</HintPath>
    </Reference>
    <Reference Include="ByamlExt, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Toolbox\Lib\ByamlExt.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="CSCore">
      <HintPath>..\Toolbox\Lib\CSCore.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="CsvHelper">
      <HintPath>..\Toolbox\Lib\CsvHelper.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="EditorCoreCommon">
      <HintPath>..\Toolbox\Lib\EditorCoreCommon.dll</HintPath>
    </Reference>
    <Reference Include="FlatBuffers">
      <HintPath>..\Toolbox\Lib\FlatBuffers.dll</HintPath>
    </Reference>
    <Reference Include="Gl_EditorFramework">
      <HintPath>..\Toolbox\Gl_EditorFramework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="KclLibrary">
      <HintPath>..\Toolbox\Lib\KclLibrary.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="KclLibraryGUI">
      <HintPath>..\Toolbox\Lib\KclLibraryGUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="NAudio">
      <HintPath>..\Toolbox\Lib\NAudio.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Toolbox\Lib\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ObjectListView">
      <HintPath>..\Toolbox\Lib\ObjectListView.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenTK, Version=3.0.1.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Toolbox\Lib\OpenTK.dll</HintPath>
    </Reference>
    <Reference Include="OpenTK.GLControl, Version=3.0.1.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Toolbox\Lib\OpenTK.GLControl.dll</HintPath>
    </Reference>
    <Reference Include="SARCExt">
      <HintPath>..\Toolbox\Lib\SARCExt.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SELib">
      <HintPath>..\Toolbox\Lib\SELib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SFGraphics">
      <HintPath>..\Toolbox\Lib\SFGraphics.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SFGraphics.Utils">
      <HintPath>..\Toolbox\Lib\SFGraphics.Utils.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SharpYaml">
      <HintPath>..\Toolbox\Lib\SharpYaml.dll</HintPath>
    </Reference>
    <Reference Include="SPICA">
      <HintPath>..\Toolbox\Lib\SPICA.dll</HintPath>
    </Reference>
    <Reference Include="SPICA.Rendering">
      <HintPath>..\Toolbox\Lib\SPICA.Rendering.dll</HintPath>
    </Reference>
    <Reference Include="SuperBMDLib">
      <HintPath>..\Toolbox\Lib\SuperBMDLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Syroot.BinaryData">
      <HintPath>..\Toolbox\Lib\Syroot.BinaryData.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Syroot.Maths">
      <HintPath>..\Toolbox\Lib\Syroot.Maths.dll</HintPath>
    </Reference>
    <Reference Include="Syroot.NintenTools.Bfres">
      <HintPath>..\Toolbox\Lib\Syroot.NintenTools.Bfres.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Syroot.NintenTools.MarioKart8">
      <HintPath>..\Toolbox\Lib\Syroot.NintenTools.MarioKart8.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Syroot.NintenTools.NSW.Bfres">
      <HintPath>..\Toolbox\Lib\Syroot.NintenTools.NSW.Bfres.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Syroot.NintenTools.NSW.Bntx">
      <HintPath>..\Toolbox\Lib\Syroot.NintenTools.NSW.Bntx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Messaging" />
    <Reference Include="VGAudio">
      <HintPath>..\Toolbox\Lib\VGAudio.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ZeldaLib">
      <HintPath>..\Toolbox\Lib\ZeldaLib.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="GUI\BCH\BCHAnimationEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BCH\BCHMeshEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BCH\BCHModelEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BCH\BCHBoneEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BCH\Material\BCHMaterialGeneralEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BCH\Material\BCHMaterialShaderParamEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BCH\Material\BCHMaterialEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BCH\Material\BCHMaterialColorEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BCH\Material\BCHMaterialBlendingEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BCH\Material\BCHMaterialFragmentEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BCH\Material\BCHTextureMapEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BCH\MetaData\UserDataEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BXFNT\CharacterSelector.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Materials\CTR\PaneMatColorEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Materials\CTR\PaneMatCTRTevEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Materials\Rev\PaneMatBlending.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Materials\Rev\PaneMatColorEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Materials\Rev\PaneMatRevTevSwapTableEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Materials\Rev\PaneMatRevTevEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Materials\Rev\SwapTableEntry.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\RenderState\RenderStateEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\ShaderParams\TexSrtPanel2D.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\GFBMDL\GFLXMaterialEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\GFBMDL\GFLXMaterialParamEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\GFBMDL\GFLXMeshEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\ViewportEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Animations\Basic\LayoutAnimEditorBasic.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Animations\LytAnimEditorKeyGUI.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Animations\LytKeyPaneSRTPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Animations\LytKeyVisibiltyPane.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Animations\LytKeyVtxColorPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\BasePaneEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\BasePictureboxEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\EditorPanelBase.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Materials\PaneMatBlending.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Materials\PaneMatTextureCombiner.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Materials\PaneMatColorEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Materials\PaneMatTextureMapsEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Part\PartPaneEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\TextEditor\PaneTextBoxEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\VertexColorPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Window\WindowContentEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Window\WindowFrameEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Window\WindowPaneEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Window\WindowFrameEditorSettings.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\Editor\Window\WindowFrameSelector.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\LayoutViewer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFLYT\UserDataEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BotwActorEditorControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BXFNT\BffntEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\AAMP\AampEditorBase.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Byaml\MuuntEditor\MuuntEditor3D.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Byaml\MuuntEditor\MuuntEditor2D.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\PTCL\Color8KeySlider.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="GUI\Editors\PTCL\ColorConstantPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\PTCL\EmitterTexturePanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\PTCL\ColorRandomPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\PTCL\EmitterEditorNX.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\BoneVisualAnims\BoneVisualAnimEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\ShaderParams\ParamValueEditorBase.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\ShaderParams\booleanPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Texture Sampler\SamplerEditorSimple.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Byaml\TurboCourseMuunt\TurboMunntEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\EffectTableEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Message\MSBTEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\AAMP\AampEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\BfresEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\BfresHeaderEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\BoneAnimEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\ShaderParams\ColorWheel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\ShaderParams\ShaderParamEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\ShaderParams\TexSrtPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\ShaderParams\vector1SliderPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\ShaderParams\vector2SliderPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\ShaderParams\vector3SliderPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\ShaderParams\vector4SliderPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Shape\KeyShapeList.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Shape\VertexBufferList.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Skeleton\BoneInfoPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\BoneAnims\BoneAnimEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Shape\BfresShapeEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\SubFileEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\ShaderAssign\ShaderOptionsEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\NewFolder1\SamplerEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\RenderStateEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\SamplerEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\RenderInfoEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\TexturePattern\FrameTextureThumbnail.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\ParamAnim\AnimParamEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Scene\SceneAnimEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\ShaderBinaryDisplay.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\ShaderEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\TexturePatternAnimEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\UserDataEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Advanced Editor\TextureViewer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\MK8TrackEditor\MK8MapCameraEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\BFAVEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Skeleton\BfresBoneEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Materials\BfresMaterialEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Editors\VisibiltyAnimEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\TextureLoader.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\Byaml\ByamlEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\BFRES\Skeleton\FSKLEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BrawlboxHelper\BrawlboxHelper.csproj" />
    <ProjectReference Include="..\Switch_Toolbox_Library\Toolbox_Library.csproj" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
  <ItemGroup>
    <COMReference Include="AxWMPLib">
      <Guid>{6BF52A50-394A-11D3-B153-00C04F79FAA6}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>aximp</WrapperTool>
      <Isolated>False</Isolated>
      <Private>False</Private>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Texture.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="FileFormats\EvemtFlow\" />
    <Folder Include="FileFormats\NLG\Common\" />
    <Folder Include="FileFormats\Pokemon\GFL2\" />
    <Folder Include="GUI\Byaml\MuuntEditor\Renderables\" />
    <Folder Include="GUI\Rom\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\MetaInfo.png" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\Hashes\Pkmn.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DockPanelSuite" Version="3.0.6" />
    <PackageReference Include="DockPanelSuite.ThemeVS2015" Version="3.0.6" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="5.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageReference Include="ZstdSharp.Port" Version="0.7.2" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="FileFormats\BFRES\Bfres Structs\BfresStructs.cs" />
    <Compile Remove="FileFormats\BFRES\BfresStructs.cs" />
    <Compile Remove="GUI\Editors\BFRESPreview.cs" />
    <Compile Remove="GUI\Editors\BFRESPreview.Designer.cs" />
    <Compile Remove="GUI\TextureUI\GTXImporterSettings.cs" />
    <Compile Remove="GUI\TextureUI\GTXTextureImporter.cs" />
    <EmbeddedResource Remove="GUI\BfresRenderInfo.resx" />
    <EmbeddedResource Remove="GUI\Editors\BFRESPreview.resx" />
  </ItemGroup>
</Project>